name: lcdnet
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2023.01.10=h06a4308_0
  - certifi=2022.12.7=py37h06a4308_0
  - cudatoolkit=11.3.1=h9edb442_10
  - faiss-cpu=1.7.3=py3.7_h2a577fa_0_cpu
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.10.4=h0708190_1
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - intel-openmp=2021.4.0=h06a4308_3561
  - jbig=2.1=h7f98852_2003
  - jpeg=9e=h166bdaf_1
  - lame=3.100=h7f98852_1001
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=2.2.1=h9c3ff4c_0
  - libdeflate=1.7=h7f98852_5
  - libfaiss=1.7.3=h2bc3f7f_0_cpu
  - libffi=3.4.2=h6a678d5_6
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.17=h166bdaf_0
  - libpng=1.6.37=h21135ba_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.3.0=hf544144_1
  - libuv=1.43.0=h7f98852_0
  - libwebp-base=1.2.2=h7f98852_1
  - lz4-c=1.9.3=h9c3ff4c_1
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py37h402132d_0
  - mkl_fft=1.3.1=py37h3e078e5_1
  - mkl_random=1.2.2=py37h219a48f_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.6=he412f7d_0
  - numpy-base=1.21.5=py37ha15fc14_3
  - olefile=0.46=pyh9f0ad1d_1
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1s=h7f8727e_0
  - pillow=8.3.2=py37h0f21c89_0
  - pip=22.3.1=py37h06a4308_0
  - python=3.7.16=h7a1cb2a_0
  - python_abi=3.7=2_cp37m
  - pytorch=1.10.1=py3.7_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - readline=8.2=h5eee18b_0
  - setuptools=65.6.3=py37h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.40.1=h5082296_0
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=0.10.1=py37_cu113
  - torchvision=0.11.2=py37_cu113
  - typing_extensions=4.4.0=pyha770c72_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.10=h5eee18b_1
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.0=ha95c52a_0
  - pip:
      - addict==2.4.0
      - aiofiles==22.1.0
      - aiosqlite==0.18.0
      - anyio==3.6.2
      - appdirs==1.4.4
      - argon2-cffi==21.3.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.2.3
      - attrs==22.2.0
      - babel==2.11.0
      - backcall==0.2.0
      - beautifulsoup4==4.11.2
      - beniget==0.4.1
      - bleach==6.0.0
      - cached-property==1.5.2
      - ccimport==0.3.7
      - cffi==1.15.1
      - charset-normalizer==3.0.1
      - click==8.1.3
      - cloudpickle==2.2.1
      - configargparse==1.5.3
      - cumm-cu113==0.2.9
      - cycler==0.11.0
      - cython==0.29.33
      - dash==2.8.1
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - debugpy==1.6.6
      - decorator==5.1.1
      - defusedxml==0.7.1
      - deprecation==2.1.0
      - docker-pycreds==0.4.0
      - easydict==1.10
      - entrypoints==0.4
      - fastjsonschema==2.16.2
      - fire==0.5.0
      - flask==2.2.2
      - fonttools==4.38.0
      - fqdn==1.5.1
      - gast==0.5.3
      - gitdb==4.0.10
      - gitpython==3.1.30
      - h5py==3.8.0
      - idna==3.4
      - importlib-metadata==6.0.0
      - importlib-resources==5.10.2
      - ipykernel==6.16.2
      - ipython==7.34.0
      - ipython-genutils==0.2.0
      - ipywidgets==8.0.4
      - isoduration==20.11.0
      - itsdangerous==2.1.2
      - jedi==0.18.2
      - jinja2==3.1.2
      - joblib==1.2.0
      - json5==0.9.11
      - jsonpointer==2.3
      - jsonschema==4.17.3
      - jupyter-client==7.4.9
      - jupyter-core==4.12.0
      - jupyter-events==0.5.0
      - jupyter-packaging==0.12.3
      - jupyter-server==1.23.5
      - jupyter-server-fileid==0.6.0
      - jupyter-server-ydoc==0.6.1
      - jupyter-ydoc==0.2.2
      - jupyterlab==3.6.1
      - jupyterlab-pygments==0.2.2
      - jupyterlab-server==2.19.0
      - jupyterlab-widgets==3.0.5
      - kiwisolver==1.4.4
      - lark==1.1.5
      - llvmlite==0.39.1
      - markupsafe==2.1.2
      - matplotlib==3.5.3
      - matplotlib-inline==0.1.6
      - mistune==2.0.4
      - nbclassic==0.5.1
      - nbclient==0.7.2
      - nbconvert==7.2.9
      - nbformat==5.5.0
      - nest-asyncio==1.5.6
      - networkx==2.6.3
      - ninja==1.11.1
      - notebook==6.5.2
      - notebook-shim==0.2.2
      - numba==0.56.4
      - numpy==1.20.0
      - open3d==0.14.1
      - opencv-python==4.7.0.68
      - packaging==23.0
      - pandas==1.3.5
      - pandocfilters==1.5.0
      - parso==0.8.3
      - pathtools==0.1.2
      - pccm==0.3.4
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pkgutil-resolve-name==1.3.10
      - plotly==5.13.0
      - ply==3.11
      - portalocker==2.7.0
      - prometheus-client==0.16.0
      - prompt-toolkit==3.0.36
      - protobuf==3.20.1
      - psutil==5.9.4
      - ptyprocess==0.7.0
      - pybind11==2.10.3
      - pycparser==2.21
      - pygments==2.14.0
      - pykitti==0.3.1
      - pyparsing==3.0.9
      - pyquaternion==0.9.9
      - pyrsistent==0.19.3
      - python-dateutil==2.8.2
      - python-json-logger==2.0.4
      - pythran==0.12.1
      - pytorch-metric-learning==2.0.0
      - pytz==2022.7.1
      - pywavelets==1.3.0
      - pyyaml==6.0
      - pyzmq==25.0.0
      - requests==2.28.2
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - scikit-image==0.14.5
      - scikit-learn==1.0.2
      - scipy==1.7.3
      - send2trash==1.8.0
      - sentry-sdk==1.14.0
      - setproctitle==1.3.2
      - sharedarray==3.2.2
      - smmap==5.0.0
      - sniffio==1.3.0
      - soupsieve==2.3.2.post1
      - spconv-cu113==2.1.25
      - tenacity==8.1.0
      - tensorboardx==2.5.1
      - termcolor==2.2.0
      - terminado==0.17.1
      - threadpoolctl==3.1.0
      - tinycss2==1.2.1
      - tomli==2.0.1
      - tomlkit==0.11.6
      - tornado==6.2
      - tqdm==4.64.1
      - traitlets==5.9.0
      - uri-template==1.2.0
      - urllib3==1.26.14
      - wandb==0.13.9
      - wcwidth==0.2.6
      - webcolors==1.12
      - webencodings==0.5.1
      - websocket-client==1.5.0
      - werkzeug==2.2.2
      - widgetsnbextension==4.0.5
      - y-py==0.5.5
      - ypy-websocket==0.8.2
      - zipp==3.12.0
